///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SimpleCalculator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SimpleCalculatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("f3bff44b-8b3d-4ff6-bc47-d7b960e10b74")]
    public partial class SimpleCalculatorRepository : RepoGenBaseFolder
    {
        static SimpleCalculatorRepository instance = new SimpleCalculatorRepository();
        SimpleCalculatorRepositoryFolders.ExplorerAppFolder _explorer;
        SimpleCalculatorRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the SimpleCalculatorRepository element repository.
        /// </summary>
        [RepositoryFolder("f3bff44b-8b3d-4ff6-bc47-d7b960e10b74")]
        public static SimpleCalculatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SimpleCalculatorRepository() 
            : base("SimpleCalculatorRepository", "/", null, 0, false, "f3bff44b-8b3d-4ff6-bc47-d7b960e10b74", ".\\RepositoryImages\\SimpleCalculatorRepositoryf3bff44b.rximgres")
        {
            _explorer = new SimpleCalculatorRepositoryFolders.ExplorerAppFolder(this);
            _calculator = new SimpleCalculatorRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f3bff44b-8b3d-4ff6-bc47-d7b960e10b74")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("8089e669-ce04-4142-88e7-7fc3c6d52a15")]
        public virtual SimpleCalculatorRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("f0e65089-b5c3-4f61-9a00-465bef139ec3")]
        public virtual SimpleCalculatorRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class SimpleCalculatorRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("8089e669-ce04-4142-88e7-7fc3c6d52a15")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _calculator1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "8089e669-ce04-4142-88e7-7fc3c6d52a15", "")
            {
                _calculator1runningwindowInfo = new RepoItemInfo(this, "Calculator1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^Calculator\\ -\\ 1\\ running\\ wi']", 30000, null, "109ff260-fe9c-4ea0-b098-d2b15555c6c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8089e669-ce04-4142-88e7-7fc3c6d52a15")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8089e669-ce04-4142-88e7-7fc3c6d52a15")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Calculator1RunningWindow item.
            /// </summary>
            [RepositoryItem("109ff260-fe9c-4ea0-b098-d2b15555c6c8")]
            public virtual Ranorex.Button Calculator1RunningWindow
            {
                get
                {
                    return _calculator1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Calculator1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("109ff260-fe9c-4ea0-b098-d2b15555c6c8")]
            public virtual RepoItemInfo Calculator1RunningWindowInfo
            {
                get
                {
                    return _calculator1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("f0e65089-b5c3-4f61-9a00-465bef139ec3")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num8buttonInfo;
            RepoItemInfo _plusbuttonInfo;
            RepoItemInfo _text8Info;
            RepoItemInfo _sometextInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "f0e65089-b5c3-4f61-9a00-465bef139ec3", "")
            {
                _num8buttonInfo = new RepoItemInfo(this, "Num8Button", "?/?/button[@automationid='num8Button']", 30000, null, "e5d99daf-1804-4fee-b73c-d0c290b1bef6");
                _plusbuttonInfo = new RepoItemInfo(this, "PlusButton", "?/?/button[@automationid='plusButton']", 30000, null, "41d5265b-29ae-49cb-8a73-4b5130ed605a");
                _text8Info = new RepoItemInfo(this, "Text8", "?/?/button[@automationid='num8Button']/text[@name='8']", 30000, null, "210059f5-5e3f-4458-b467-0d30c81d07a7");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "?/?/button[@automationid='equalButton']/text[@name='']", 30000, null, "cdf44f86-bdaa-4895-aa4b-b20f79ed6f8f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f0e65089-b5c3-4f61-9a00-465bef139ec3")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f0e65089-b5c3-4f61-9a00-465bef139ec3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num8Button item.
            /// </summary>
            [RepositoryItem("e5d99daf-1804-4fee-b73c-d0c290b1bef6")]
            public virtual Ranorex.Button Num8Button
            {
                get
                {
                    return _num8buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num8Button item info.
            /// </summary>
            [RepositoryItemInfo("e5d99daf-1804-4fee-b73c-d0c290b1bef6")]
            public virtual RepoItemInfo Num8ButtonInfo
            {
                get
                {
                    return _num8buttonInfo;
                }
            }

            /// <summary>
            /// The PlusButton item.
            /// </summary>
            [RepositoryItem("41d5265b-29ae-49cb-8a73-4b5130ed605a")]
            public virtual Ranorex.Button PlusButton
            {
                get
                {
                    return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusButton item info.
            /// </summary>
            [RepositoryItemInfo("41d5265b-29ae-49cb-8a73-4b5130ed605a")]
            public virtual RepoItemInfo PlusButtonInfo
            {
                get
                {
                    return _plusbuttonInfo;
                }
            }

            /// <summary>
            /// The Text8 item.
            /// </summary>
            [RepositoryItem("210059f5-5e3f-4458-b467-0d30c81d07a7")]
            public virtual Ranorex.Text Text8
            {
                get
                {
                    return _text8Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text8 item info.
            /// </summary>
            [RepositoryItemInfo("210059f5-5e3f-4458-b467-0d30c81d07a7")]
            public virtual RepoItemInfo Text8Info
            {
                get
                {
                    return _text8Info;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("cdf44f86-bdaa-4895-aa4b-b20f79ed6f8f")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("cdf44f86-bdaa-4895-aa4b-b20f79ed6f8f")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}